default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: music_dev123
  # database: staging_bench_dev123
  username: postgres
  password: 123456789

test: &test
  <<: *default
  database: music_test
  username: postgres
  password: 123456789
  
